### ISSUE TITLE
After updated to version 0.4.0 the task crashed

### ISSUE THREAD

**Issue by hassegawa** [fakhrulhilal/TFSGitDownloader#10]
##[error]File not found: 'D:\a\_tasks\GitDownloader_56033f91-aeb8-4316-b19a-bcb721f4705b\0.4.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'

![image](https://user-images.githubusercontent.com/4307929/65173999-6505c480-da26-11e9-992e-f1a8d61a4eb5.png)

**Comment by JeffMcCabe** [comment]
+1 We're also having this issue

**Comment by RogueOverride** [comment]
+1 Same issue here.

**Comment by jrlichina** [comment]
+1 Same issue here.

**Comment by nexocentric** [comment]
I am also having that issue. Is it possible to roll back for a little bit?

**Comment by jrlichina** [comment]
It also shows it pulled from the marketplace.  I uninstalled it and now I can't get it back.

https://marketplace.visualstudio.com/items?itemName=fakhrulhilal-maktum.GitDownloader

**Comment by fakhrulhilal** [comment]
Please update again to latest version 0.4.7. I'll close this issue if no one report this error within 3 days.

**Comment by hassegawa** [comment]
it's working again. Thanks
