### ISSUE TITLE
Old task execution support library is used

### ISSUE THREAD

**Issue by pixelicous** [fakhrulhilal/TFSGitDownloader#11]
We upgraded our Azure Devops self hosted agents to use 2.161.0, since then we get the following warning in our release logs - 
#[warning]Task 'GitDownloader' (1.0.17) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

Are we using an older version? The github released version seem to be of different order..

**Comment by fakhrulhilal** [comment]
You're using unknown version of GitDownloader extension. Currently, the latest version is 0.4.7. Can you check issue #8 as well?

**Comment by fakhrulhilal** [comment]
The issue isn’t clear
