### ISSUE TITLE
Tabs and spaces - not a real bug

### ISSUE THREAD

**Issue by itsho** [fakhrulhilal/TFSGitDownloader#12]
Hi.

Your task is **very** useful. thank you!

There's an inconsistency in the code. sometimes it uses tabs and sometimes it uses spaces.

In this line (and the next 6 lines), there's a tab instead of spaces:
https://github.com/fakhrulhilal/TFSGitDownloader/blob/2c8b2668de78966871140b8bd4d0b2568338eaf9/GitDownloader/GitDownloader.ps1#L132

I'm **not** trying to nitpick! The only reason I'm opening this issue is that when using this code inside of a _"Run Inline Powershell"_ task, Azure will refuse to run the code with the following error:
>TF20507: The string argument contains a character that is not valid:'u0009'. Correct the argument, and then try the operation again.
>Parameter name: definition.Steps.Script

It took me some time to understand that ASCII code 9 (tab) is not accepted in this task, and it also took some time to find the source of it.

To be clear - I understand that this is not a real bug, and that I can run your task directly, but when I tried to modify it and manually test - it fails from the reason I mentioned above.

Thank you.

**Comment by fakhrulhilal** [comment]
Can you give your full example when using this extension? I ever deal with this kind of error. Mostly, it’s caused by tab character when filling plugin parameter. Just to make sure, please recheck again for every plugin parameter (could be in the begining/ending of config value). So it’s not specific to this extension only. 
Of it doesn’t solve your issue, please let me know.

**Comment by itsho** [comment]
The task I was using is "[Run Inline Powershell](https://marketplace.visualstudio.com/items?itemName=petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Build-InlinePowershell)" (source is [here](https://github.com/XpiritBV/Vsts-Build-Task-InlinePowershell))

To reproduce the issue, add the mentioned task, and paste this line:
https://github.com/fakhrulhilal/TFSGitDownloader/blob/2c8b2668de78966871140b8bd4d0b2568338eaf9/GitDownloader/GitDownloader.ps1#L132

Then, try to save the build definition, and you'll see the error.

See example:
![invalidArgumentTab](https://user-images.githubusercontent.com/1774797/71674475-f570d680-2d83-11ea-8c30-aa90870922ac.png)


So I'd say it's actually not a bug in your repo, but instead - in the repo I mentioned above - so I'll open a bug in the other one.

Thank you
